version: "3.8"

services:
  # Servidor do Banco de Dados MySQL 8.0
  db:
    image: mysql:8.0.33
    container_name: store_manager_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: StoreManager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - store_manager_net

  # API Store Manager conectada ao container MySQL
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store_manager_api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/StoreManager
    networks:
      - store_manager_net

volumes:
  mysql_data:

networks:
  store_manager_net:
    driver: bridge
